project_name: vault-kubernetes
release:
  github:
    owner: harkeet
    name: vault-kubernetes
builds:
    - id: synchronizer
      goos:
        - linux
      goarch:
        - amd64
        - arm64
      main: ./cmd/synchronizer/
      binary: synchronizer
      env:
        - CGO_ENABLED=0
    - id: authenticator
      goos:
        - linux
      goarch:
        - amd64
        - arm64
      main: ./cmd/authenticator/
      binary: authenticator
      env:
        - CGO_ENABLED=0
    - id: token-renewer
      goos:
        - linux
      goarch:
        - amd64
        - arm64
      main: ./cmd/token-renewer/
      binary: token-renewer
      env:
        - CGO_ENABLED=0
dockers:
    - ids:
        - synchronizer
      goos: linux
      goarch: amd64
      dockerfile: packaging/docker/synchronizer/Dockerfile
      use: buildx
      image_templates:
        - harkeet/{{ .ProjectName }}-synchronizer:{{ .Major }}.{{ .Minor }}.{{ .Patch }}
        - harkeet/{{ .ProjectName }}-synchronizer:{{ .Major }}.{{ .Minor }}
        - harkeet/{{ .ProjectName }}-synchronizer:latest
      build_flag_templates:
        - --label=org.opencontainers.image.created={{ .Date }}
        - --label=org.opencontainers.image.revision={{ .ShortCommit }}
        - --label=org.opencontainers.image.source={{ .GitURL }}
        - --label=org.opencontainers.image.url={{ .GitURL }}
        - --label=org.opencontainers.image.vendor=PostFinance AG
        - --label=org.opencontainers.image.version={{ .Version }}
        - --pull
    - ids:
        - synchronizer
      goos: linux
      goarch: arm64
      dockerfile: packaging/docker/synchronizer/Dockerfile
      use: buildx
      image_templates:
        - harkeet/{{ .ProjectName }}-synchronizer:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64
        - harkeet/{{ .ProjectName }}-synchronizer:{{ .Major }}.{{ .Minor }}-arm64
        - harkeet/{{ .ProjectName }}-synchronizer:latest-arm64
      build_flag_templates:
        - --platform=linux/arm64
        - --label=org.opencontainers.image.created={{ .Date }}
        - --label=org.opencontainers.image.revision={{ .ShortCommit }}
        - --label=org.opencontainers.image.source={{ .GitURL }}
        - --label=org.opencontainers.image.url={{ .GitURL }}
        - --label=org.opencontainers.image.vendor=PostFinance AG
        - --label=org.opencontainers.image.version={{ .Version }}
        - --pull
    - ids:
        - authenticator
      goos: linux
      goarch: amd64
      dockerfile: packaging/docker/authenticator/Dockerfile
      use: buildx
      image_templates:
        - harkeet/{{ .ProjectName }}-authenticator:{{ .Major }}.{{ .Minor }}.{{ .Patch }}
        - harkeet/{{ .ProjectName }}-authenticator:{{ .Major }}.{{ .Minor }}
        - harkeet/{{ .ProjectName }}-authenticator:latest
      build_flag_templates:
        - --label=org.opencontainers.image.created={{ .Date }}
        - --label=org.opencontainers.image.revision={{ .ShortCommit }}
        - --label=org.opencontainers.image.source={{ .GitURL }}
        - --label=org.opencontainers.image.url={{ .GitURL }}
        - --label=org.opencontainers.image.vendor=PostFinance AG
        - --label=org.opencontainers.image.version={{ .Version }}
        - --pull
    - ids:
        - authenticator
      goos: linux
      goarch: arm64
      dockerfile: packaging/docker/authenticator/Dockerfile
      use: buildx
      image_templates:
        - harkeet/{{ .ProjectName }}-authenticator:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64
        - harkeet/{{ .ProjectName }}-authenticator:{{ .Major }}.{{ .Minor }}-arm64
        - harkeet/{{ .ProjectName }}-authenticator:latest-arm64
      build_flag_templates:
        - --platform=linux/arm64
        - --label=org.opencontainers.image.created={{ .Date }}
        - --label=org.opencontainers.image.revision={{ .ShortCommit }}
        - --label=org.opencontainers.image.source={{ .GitURL }}
        - --label=org.opencontainers.image.url={{ .GitURL }}
        - --label=org.opencontainers.image.vendor=PostFinance AG
        - --label=org.opencontainers.image.version={{ .Version }}
        - --pull
    - ids:
        - token-renewer
      goos: linux
      goarch: amd64
      dockerfile: packaging/docker/token-renewer/Dockerfile
      use: buildx
      image_templates:
        - harkeet/{{ .ProjectName }}-token-renewer:{{ .Major }}.{{ .Minor }}.{{ .Patch }}
        - harkeet/{{ .ProjectName }}-token-renewer:{{ .Major }}.{{ .Minor }}
        - harkeet/{{ .ProjectName }}-token-renewer:latest
      build_flag_templates:
        - --label=org.opencontainers.image.created={{ .Date }}
        - --label=org.opencontainers.image.revision={{ .ShortCommit }}
        - --label=org.opencontainers.image.source={{ .GitURL }}
        - --label=org.opencontainers.image.url={{ .GitURL }}
        - --label=org.opencontainers.image.vendor=PostFinance AG
        - --label=org.opencontainers.image.version={{ .Version }}
        - --pull
    - ids:
        - token-renewer
      goos: linux
      goarch: arm64
      dockerfile: packaging/docker/token-renewer/Dockerfile
      use: buildx
      image_templates:
        - harkeet/{{ .ProjectName }}-token-renewer:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64
        - harkeet/{{ .ProjectName }}-token-renewer:{{ .Major }}.{{ .Minor }}-arm64
        - harkeet/{{ .ProjectName }}-token-renewer:latest-arm64
      build_flag_templates:
        - --platform=linux/arm64
        - --label=org.opencontainers.image.created={{ .Date }}
        - --label=org.opencontainers.image.revision={{ .ShortCommit }}
        - --label=org.opencontainers.image.source={{ .GitURL }}
        - --label=org.opencontainers.image.url={{ .GitURL }}
        - --label=org.opencontainers.image.vendor=PostFinance AG
        - --label=org.opencontainers.image.version={{ .Version }}
        - --pull
snapshot:
  # https://goreleaser.com/customization/snapshots/
  name_template: "{{ incpatch .Version }}-SNAPSHOT"
